### ISSUE TITLE
module parse-server-mailgun not found

### ISSUE THREAD

**Issue by abhishekmishra07** [sebsylvester/parse-server-mailgun#13]
I am running parse-server v2.3.1 and receives the below error.

```
Error: Cannot find module 'parse-server-mailgun'
2017-01-09T13:49:01.193976+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:470:15)
2017-01-09T13:49:01.193983+00:00 app[web.1]:     at Function.Module._load (module.js:418:25)
2017-01-09T13:49:01.193984+00:00 app[web.1]:     at Module.require (module.js:498:17)
2017-01-09T13:49:01.193984+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-09T13:49:01.193991+00:00 app[web.1]:     at loadAdapter (/app/node_modules/parse-server/lib/Adapters/AdapterLoader.js:27:15)
2017-01-09T13:49:01.193992+00:00 app[web.1]:     at loadAdapter (/app/node_modules/parse-server/lib/Adapters/AdapterLoader.js:34:12)
2017-01-09T13:49:01.193993+00:00 app[web.1]:     at new ParseServer (/app/node_modules/parse-server/lib/ParseServer.js:279:65)
2017-01-09T13:49:01.194005+00:00 app[web.1]:     at new _ParseServer (/app/node_modules/parse-server/lib/index.js:46:16)
2017-01-09T13:49:01.194006+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:15:11)
2017-01-09T13:49:01.194006+00:00 app[web.1]:     at Module._compile (module.js:571:32)


```
The adapter configuration looks like this

```
emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
            // The address that your emails come from
      fromAddress:xxxxx,
      // Your domain from mailgun.com
      domain: xxxxx,
      // Your API key from mailgun.com
      apiKey: ******,
      templates: {
        transactionEmail: {
          subject: 'Urgent notification!',
          pathPlainText: resolve(__dirname, 'path/to/templates/custom_alert.txt'),
          pathHtml: resolve(__dirname, 'path/to/templates/custom_alert.html'),
        }
      }
    }
  }

```

I have checked "parse-server-mailgun" package is available in node_modules. But the error persists.

**Comment by sebsylvester** [comment]
I can't reproduce the error. On my end everything seems ok.
You could create a test repo with the code, that might allow me to reproduce the error.

**Comment by sebsylvester** [comment]
By the way. Are those error logs from Heroku or some other deployment environment? 
If that's the case, double-check the presence of all dependencies.

**Comment by abhishekmishra07** [comment]
Parse-Server is deployed to Heroku and the package.json contains parse-server-mailgun. node_module has parse-server-mailgun in it. But with every 'node index.js' the same error gets thrown.

**Comment by abhishekmishra07** [comment]
I checked the dependencies loadash / co and mailgun-js and mail composer are installed as part of main package.json ( parse-server ).

**Comment by sebsylvester** [comment]
Try a regular require of the parse-server-module, outside of the Parse Server config. 
Test this locally and remote.

**Comment by abhishekmishra07** [comment]
Ok. I am going to try that. Where does parse-server reads the module info from. ? I tried replacing the module: 'parse-server-mailgun' with module: 'parse-server-mailgun-adapter-template' and it works.

**Comment by sebsylvester** [comment]
I am not sure but there is a [AdapterLoader](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/AdapterLoader.js) module. I guess this is where the MailAdapter is required and instantiated. You could set a few breakpoints in your code and debug it to be sure.

**Comment by sebsylvester** [comment]
Another option would be (don't know if this works) to pass a path to the MailAdapter directly, like `./node_modules/parse-server-mailgun/lib/MailgunAdapter`, instead of the module name.
