### ISSUE TITLE
mailgun.json doesn't work?

### ISSUE THREAD

**Issue by JEKos** [sebsylvester/parse-server-mailgun#14]
Hi, I installed the module in my parse server, I created the mailgun.json in the root folder, and I ran `node ./src/mailgun-tester` from the module's root folder and this is the error I got : 

```
/root/myparse-server/node_modules/parse-server-mailgun/src/mailgun-tester/index.js:24
    User: class User {
          ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

```

**My node version is  v5.12.0**

**Comment by JEKos** [comment]
**I upgraded to node  v6.9.4 version**
Now it says that:
```
{ Error: Free accounts are for test purposes only. Please upgrade or add the address to authorized recipients in Account Settings.
    at IncomingMessage.<anonymous> (/root/myparse-server/node_modules/parse-server-mailgun/node_modules/mailgun-js/lib/request.js:300:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) statusCode: 400 }
```

But I'm using my own custom domain name.

**Comment by sebsylvester** [comment]
Hi, I've just tested the mailgun-tester script and it couldn't reproduce any errors. I've used Node v7.4.0, but it should also work with v6.x.x.
I'm not sure what causes it, but I suspect it's because you haven't upgraded your account yet, which requires you to add a payment method.

**Comment by JEKos** [comment]
Yep,I don't have add payment method yet. If I do, can I still use free plan ? I don't think I'm gonna pass 10.000 emails per month.

**Comment by sebsylvester** [comment]
Yes you can still send 10K emails for free. But if you reserve that quota for parse server, then it should go a long way. I also use nodemailer, configured with a Gmail account. That will add plenty more free emails.

**Comment by JEKos** [comment]
Thanks for the info. Now it works without any error, but I didn't get any email to my own email address that I put for test.

**Comment by JEKos** [comment]
It took a while, but I received the email finally.

**Comment by sebsylvester** [comment]
Cool

**Comment by JEKos** [comment]
Thank you for the help!

**Comment by sebsylvester** [comment]
No problem, thanks for starring the repo 👍
