### ISSUE TITLE
Error: MailgunAdapter templates are not properly configured.

### ISSUE THREAD

**Issue by rjpalermo1** [sebsylvester/parse-server-mailgun#20]
.../samples/api-server/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:43
            throw new Error(ERRORS.bad_template_config);
            ^

Error: MailgunAdapter templates are not properly configured.

I am trying to integrate Parse as a service in another express-server (feathers.js).  All other mailgun adapters work except this one...server/parse boots fine.

Does it have to do with babel transpiler you think?  I've tried with 

`require("babel-register");` no luck.

I'm fresh to js.  would like to use this for templates.

**Comment by sebsylvester** [comment]
The error is caused by the following code:
```
if (!templates || Object.keys(templates).length === 0) {
   throw new Error(ERRORS.bad_template_config);
}
```
So, there seems to be something wrong with the ```templates``` section of the MailAdapter configuration. You could add a few log statements MailAdapter's constructor function to assert the presence of all required properties of the configuration.

**Comment by rjpalermo1** [comment]
Thank you,

I started new project from scratch and configured your library first.  Everything is aces now ~ I must have forked something up in my first run.

**Comment by amitkh6** [comment]
I am facing the same problem, not sure what is being missed

Error: MailgunAdapter templates are not properly configured.
    at new MailgunAdapter (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:38:19)
    at loadAdapter (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Adapters/AdapterLoader.js:31:16)
    at loadAdapter (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Adapters/AdapterLoader.js:43:12)
    at loadAdapter (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Adapters/AdapterLoader.js:45:12)
    at getUserController (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Controllers/index.js:161:65)
    at Object.getControllers (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Controllers/index.js:88:26)
    at new ParseServer (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/ParseServer.js:139:40)
    at new _ParseServer (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/index.js:54:18)
    at Object.<anonymous> (/opt/bitnami/apps/parse/htdocs/server.js:18:11)
    at Module._compile (module.js:652:30)
