### ISSUE TITLE
email sending broken on latest parse-server 2.2.22

### ISSUE THREAD

**Issue by mman** [sebsylvester/parse-server-mailgun#4]
### Issue Description

I'm running stable version of parse-server with parse-server-mailgun module to send customized welcome and password reset emails. Worked fine since beg of August.

Since yesterday when I updated to the latest 2.2.22 the password reset emails are not being sent and parse server logs the following exception:

Downgrading to 2.2.21 and 2.2.20 does not help.

The password reset emails work great in 2.2.19 which I reverted to get everything back to work.

```
#033[31merror#033[39m: Error generating response. ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7) 
 #033[31merror#033[39m: Uncaught internal server error. ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7) ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
 ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
### Steps to reproduce

```
  emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
      fromAddress: 'XXX <xxx@yyy.zzz>',
      domain: 'mg.yyy.zzz',
      apiKey: 'key-XXXXXXXXX',
      templates: {
        passwordResetEmail: {
          subject: 'Password Reset',
          pathPlainText: resolve(__dirname, 'templates/password_reset_email.txt'),
          pathHtml: resolve(__dirname, 'templates/password_reset_email.html'),
          //callback: (user) => { return { firstName: user.get('firstName') }}
          // Now you can use {{firstName}} in your templates 
        },
        verificationEmail: {
          subject: 'Welcome',
          pathPlainText: resolve(__dirname, 'templates/verification_email.txt'),
          pathHtml: resolve(__dirname, 'templates/verification_email.html'),
          //callback: (user) => { return { firstName: user.get('firstName') }}
          // Now you can use {{firstName}} in your templates 
        }
      }
    }
  },

```

#### Expected Results

Password reset email sent.

#### Actual Outcome

Password reset emails not sent, parse-server returning ERROR.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.22

**Comment by sebsylvester** [comment]
Hi there, I just patched parse-server-mailgun to 2.1.14 and successfully tested it with the parse-server 2.2.22, so it should be fine now.

**Comment by mman** [comment]
Just tried a clean ``npm install`` and looks like you are missing babel-polyfill dependence in ``package.json`` for parse-server-mailgun package... the parse server now crashes on startup with

```
Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (module.js:440:15)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:11:1)
   ...
```

**Comment by sebsylvester** [comment]
I wasn't experiencing that issue. But I will 'upgrade' babel-polyfill to a real dependency instead of just a dev dependency

**Comment by sebsylvester** [comment]
Patched it to 2.1.15. The babel-polyfill is a now a hard dependency.

**Comment by mman** [comment]
The way I understand it is that if you don't depend on it via package.json, it never gets pulled down via ``npm install`` so it is nowhere to be found. In the past ``babel-polyfill`` was itself a dependency in parse-server so your module was using it without actually depending on it, but since it's gone now from parse-server you need to hard depend on it... perhaps it was lurking in your ``node_modules/`` somewhere that it did not crash immediately...

**Comment by mman** [comment]
Thanx for your quick patches anyway, much appreciated :)
